os: linux
language: java
jdk:
  - openjdk11

services:
  - postgresql

notifications:
  email: false

before_install:
  - cd backend
  - chmod +x mvnw

install:
  - cd backend
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - psql -c 'create database pharmacydb;' -U postgres
  - psql -c "SELECT version();"

script:
  - cd backend
  - mvn package
